import { useEffect, useRef, useState } from "react";

type TowerKind = "pulse" | "cannon" | "cryo";
type Tower = { x: number; y: number; kind: TowerKind; level: number; cool: number };
type Enemy = { x: number; y: number; path: number; hp: number; max: number; speed: number; kind: "drone" | "tank" | "boss"; dead?: boolean };
type Bullet = { x: number; y: number; tx: number; ty: number; damage: number; slow: number; color: string };
const W = 720, H = 760;
const TOWERS: Record<TowerKind, { name: string; cost: number; color: string; range: number; damage: number; rate: number; slow?: number }> = { pulse: { name: "PULSE", cost: 70, color: "#54e6ff", range: 115, damage: 16, rate: .32 }, cannon: { name: "CANNON", cost: 110, color: "#ffcb5b", range: 145, damage: 38, rate: .8 }, cryo: { name: "CRYO", cost: 90, color: "#b895ff", range: 105, damage: 8, rate: .46, slow: .45 } };
const path = [{ x: -30, y: 150 }, { x: 130, y: 150 }, { x: 130, y: 300 }, { x: 310, y: 300 }, { x: 310, y: 500 }, { x: 520, y: 500 }, { x: 520, y: 610 }, { x: 750, y: 610 }];
const dist = (a: { x: number; y: number }, b: { x: number; y: number }) => Math.hypot(a.x - b.x, a.y - b.y);

export default function NeonFortressGame({ playerId, onResult, onDone }: { playerId: string; onResult: (id: string, value: number) => void; onDone: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const selectedRef = useRef<TowerKind>("pulse"); const ended = useRef(false);
  const [selected, setSelected] = useState<TowerKind>("pulse"); const [credits, setCredits] = useState(260); const [wave, setWave] = useState(1); const [lives, setLives] = useState(12); const [score, setScore] = useState(0); const [hint, setHint] = useState("Baue Verteidigungstürme und halte die Drohnen auf.");
  selectedRef.current = selected;
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d"); if (!ctx) return; const dpr = Math.min(devicePixelRatio || 1, 2); canvas.width = W * dpr; canvas.height = H * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    const towers: Tower[] = []; const enemies: Enemy[] = []; const bullets: Bullet[] = []; let raf = 0; let last = performance.now(); let elapsed = 0; let spawn = 0; let waveSpawned = 0; let currentWave = 1; let localScore = 0; let localCredits = 260; let localLives = 12;
    const drawGlow = (x: number, y: number, r: number, color: string) => { const g = ctx.createRadialGradient(x, y, 0, x, y, r); g.addColorStop(0, `${color}55`); g.addColorStop(1, `${color}00`); ctx.fillStyle = g; ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fill(); };
    const pointAt = (value: number) => { const index = Math.min(path.length - 2, Math.floor(value)); const t = value - index; return { x: path[index].x + (path[index + 1].x - path[index].x) * t, y: path[index].y + (path[index + 1].y - path[index].y) * t }; };
    const spawnEnemy = () => { const boss = currentWave % 5 === 0 && waveSpawned === 0; const tank = !boss && waveSpawned % 7 === 6; const max = boss ? 850 + currentWave * 120 : tank ? 220 + currentWave * 30 : 70 + currentWave * 12; enemies.push({ x: path[0].x, y: path[0].y, path: 0, hp: max, max, speed: boss ? 14 : tank ? 22 : 34 + currentWave * 1.5, kind: boss ? "boss" : tank ? "tank" : "drone" }); waveSpawned += 1; setCredits(localCredits += boss ? 0 : 0); };
    const end = () => { if (ended.current) return; ended.current = true; onResult(playerId, localScore); window.setTimeout(onDone, 900); };
    const placeOrUpgrade = (x: number, y: number) => { const existing = towers.find(t => dist(t, { x, y }) < 30); if (existing) { const price = 75 + existing.level * 60; if (localCredits >= price && existing.level < 4) { localCredits -= price; existing.level += 1; setCredits(localCredits); setHint(`${TOWERS[existing.kind].name} auf Stufe ${existing.level} verbessert.`); } return; } if (y < 50 || localCredits < TOWERS[selectedRef.current].cost || towers.length >= 14) { setHint(localCredits < TOWERS[selectedRef.current].cost ? "Dafür fehlen Credits." : "Hier kann kein weiterer Turm gebaut werden."); return; } const kind = selectedRef.current; if (path.some((p, i) => i < path.length - 1 && dist({ x, y }, p) < 52)) { setHint("Baue neben dem Weg, nicht auf dem Transportpfad."); return; } localCredits -= TOWERS[kind].cost; towers.push({ x, y, kind, level: 1, cool: 0 }); setCredits(localCredits); setHint(`${TOWERS[kind].name} aktiviert.`); };
    const pointer = (event: PointerEvent) => { const rect = canvas.getBoundingClientRect(); placeOrUpgrade((event.clientX - rect.left) * W / rect.width, (event.clientY - rect.top) * H / rect.height); };
    canvas.addEventListener("pointerdown", pointer);
    const loop = (now: number) => { const dt = Math.min(.04, (now - last) / 1000); last = now; elapsed += dt; spawn -= dt; if (spawn <= 0 && waveSpawned < 7 + currentWave * 2) { spawnEnemy(); spawn = Math.max(.24, 1.05 - currentWave * .035); } if (waveSpawned >= 7 + currentWave * 2 && enemies.length === 0) { currentWave += 1; waveSpawned = 0; setWave(currentWave); localCredits += 90 + currentWave * 12; setCredits(localCredits); setHint(`Welle ${currentWave} nähert sich. Bonus-Credits erhalten.`); }
      enemies.forEach(enemy => { if (enemy.dead) return; const speed = enemy.speed * dt / 160; enemy.path += speed; const p = pointAt(enemy.path); enemy.x = p.x; enemy.y = p.y; if (enemy.path >= path.length - 1) { enemy.dead = true; localLives -= enemy.kind === "boss" ? 3 : 1; setLives(localLives); if (localLives <= 0) end(); } });
      towers.forEach(tower => { tower.cool -= dt; if (tower.cool > 0) return; const cfg = TOWERS[tower.kind]; const target = enemies.filter(e => !e.dead && dist(tower, e) <= cfg.range).sort((a, b) => b.path - a.path)[0]; if (!target) return; tower.cool = cfg.rate / (1 + (tower.level - 1) * .18); bullets.push({ x: tower.x, y: tower.y, tx: target.x, ty: target.y, damage: cfg.damage * tower.level, slow: cfg.slow ?? 0, color: cfg.color }); });
      bullets.splice(0, bullets.length, ...bullets.filter(b => { const target = enemies.find(e => !e.dead && dist(e, { x: b.tx, y: b.ty }) < 34); if (target) { target.hp -= b.damage; if (b.slow) target.speed *= 1 - b.slow; if (target.hp <= 0) { target.dead = true; localScore += target.kind === "boss" ? 500 : target.kind === "tank" ? 100 : 35; localCredits += target.kind === "boss" ? 160 : 18; setScore(localScore); setCredits(localCredits); } return false; } return true; })); enemies.splice(0, enemies.length, ...enemies.filter(e => !e.dead));
      ctx.clearRect(0, 0, W, H); ctx.fillStyle = "#05091c"; ctx.fillRect(0, 0, W, H); for (let i = 0; i < 70; i += 1) { const x = (i * 97 + elapsed * (4 + i % 3)) % W; const y = (i * 53) % H; ctx.fillStyle = `rgba(120,190,255,${.15 + (i % 4) * .08})`; ctx.fillRect(x, y, i % 2 ? 1 : 2, i % 2 ? 1 : 2); } ctx.lineCap = "round"; ctx.lineWidth = 38; ctx.strokeStyle = "#101f45"; ctx.beginPath(); ctx.moveTo(path[0].x, path[0].y); path.slice(1).forEach(p => ctx.lineTo(p.x, p.y)); ctx.stroke(); ctx.lineWidth = 2; ctx.strokeStyle = "#284e84"; ctx.stroke(); path.forEach(p => { ctx.fillStyle = "#294a78"; ctx.beginPath(); ctx.arc(p.x, p.y, 7, 0, Math.PI * 2); ctx.fill(); });
      towers.forEach(t => { const cfg = TOWERS[t.kind]; drawGlow(t.x, t.y, cfg.range * .7, cfg.color); ctx.fillStyle = "#0b1530"; ctx.strokeStyle = cfg.color; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(t.x, t.y, 18 + t.level * 2, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = cfg.color; ctx.beginPath(); ctx.arc(t.x, t.y, 6 + t.level, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#fff"; ctx.font = "bold 11px monospace"; ctx.textAlign = "center"; ctx.fillText(String(t.level), t.x, t.y + 4); });
      enemies.forEach(e => { const c = e.kind === "boss" ? "#ff507c" : e.kind === "tank" ? "#ffb44e" : "#7ff3ff"; drawGlow(e.x, e.y, e.kind === "boss" ? 34 : 20, c); ctx.fillStyle = c; ctx.beginPath(); ctx.arc(e.x, e.y, e.kind === "boss" ? 17 : e.kind === "tank" ? 12 : 8, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#162344"; ctx.fillRect(e.x - 19, e.y - 27, 38, 4); ctx.fillStyle = c; ctx.fillRect(e.x - 19, e.y - 27, 38 * Math.max(0, e.hp / e.max), 4); }); bullets.forEach(b => { ctx.strokeStyle = b.color; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(b.x, b.y); ctx.lineTo(b.tx, b.ty); ctx.stroke(); });
      if (currentWave % 5 === 0 && waveSpawned === 0) { ctx.fillStyle = "#ff507c"; ctx.font = "bold 18px monospace"; ctx.textAlign = "center"; ctx.fillText("BOSS-WELLE", W / 2, 38); } if (elapsed > 480) end(); else { raf = requestAnimationFrame(loop); } };
    raf = requestAnimationFrame(loop); return () => { cancelAnimationFrame(raf); canvas.removeEventListener("pointerdown", pointer); };
  }, [onDone, onResult, playerId]);
  return <div className="game-stage neon-stage"><div className="stage-title"><span>NEON FORTRESS / DEFENSE GRID</span><span>LIVE SCORE {score.toLocaleString("de-DE")}</span></div><div className="neon-hud"><span>WELLE <b>{wave}</b></span><span>CORE <b>{lives}</b></span><span>CREDITS <b>{credits}</b></span></div><div className="neon-canvas-wrap"><canvas ref={canvasRef} className="neon-canvas" /></div><div className="neon-toolbar">{(Object.keys(TOWERS) as TowerKind[]).map(kind => <button key={kind} type="button" className={selected === kind ? "active" : ""} onClick={() => { setSelected(kind); selectedRef.current = kind; }}><i style={{ background: TOWERS[kind].color }} /><strong>{TOWERS[kind].name}</strong><small>{TOWERS[kind].cost} C</small></button>)}</div><p className="neon-hint">{hint} <span>Turm anklicken = upgraden · Karte antippen = bauen</span></p></div>;
}
